
server:
  port: 8762

spring:
  profiles: eureka2
eureka:
  instance:
    hostname: eureka2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/

