
server:
  port: 8761

spring:
  profiles: eureka1
eureka:
  instance:
    hostname: eureka1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka2:8762/eureka/

